export const STATES_POPULATION = {
  AK: 4903185,
  AL: 731545,
  AR: 7278717,
  AS: 55519,
  AZ: 3017804,
  CA: 39512223,
  CO: 5758736,
  CT: 3565287,
  DC: 973764,
  DE: 705749,
  FL: 21477737,
  GA: 10617423,
  GU: 159398,
  HI: 1415872,
  IA: 1787065,
  ID: 12671821,
  IL: 6732219,
  IN: 3155070,
  KS: 2913314,
  KY: 4467673,
  LA: 4648794,
  MA: 6892503,
  MD: 6045680,
  ME: 1344212,
  MI: 9986857,
  MN: 5639632,
  MO: 2976149,
  MP: 55883,
  MS: 6137428,
  MT: 1068778,
  NC: 10488084,
  ND: 762062,
  NE: 1934408,
  NH: 1359711,
  NJ: 8882190,
  NM: 2096829,
  NV: 3080156,
  NY: 19453561,
  OH: 11689100,
  OK: 3956971,
  OR: 4217737,
  PA: 12801989,
  PR: 3193694,
  RI: 1059361,
  SC: 5148714,
  SD: 884659,
  TN: 6829174,
  TX: 28995881,
  UT: 3205958,
  VA: 8535519,
  VI: 104405,
  VT: 623989,
  WA: 7614893,
  WI: 5822434,
  WV: 1792147,
  WY: 578759,
};

export const STATES_NAMES = {
  USA: "Total U.S.",
  AL: "Alabama",
  AK: "Alaska",
  AS: "American Samoa",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of, Columbia",
  FL: "Florida",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: " North Dakota",
  MP: " Northern Mariana Islands",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  VI: "U.S. Virgin Islands",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

export const EMPTY_TILE_MAP = [
  {
    "hc-a2": "AL",
    name: "Alabama",
    region: "South",
    x: 6,
    y: 7,
    value: 0,
  },
  {
    "hc-a2": "AK",
    name: "Alaska",
    region: "West",
    x: 0,
    y: 0,
    value: 0,
  },
  {
    "hc-a2": "AZ",
    name: "Arizona",
    region: "West",
    x: 5,
    y: 3,
    value: 0,
  },
  {
    "hc-a2": "AR",
    name: "Arkansas",
    region: "South",
    x: 5,
    y: 6,
    value: 0,
  },
  {
    "hc-a2": "CA",
    name: "California",
    region: "West",
    x: 5,
    y: 2,
    value: 0,
  },
  {
    "hc-a2": "CO",
    name: "Colorado",
    region: "West",
    x: 4,
    y: 3,
    value: 0,
  },
  {
    "hc-a2": "CT",
    name: "Connecticut",
    region: "Northeast",
    x: 3,
    y: 11,
    value: 0,
  },
  {
    "hc-a2": "DE",
    name: "Delaware",
    region: "South",
    x: 4,
    y: 9,
    value: 0,
  },
  {
    "hc-a2": "DC",
    name: "District of Columbia",
    region: "South",
    x: 4,
    y: 10,
    value: 0,
  },
  {
    "hc-a2": "FL",
    name: "Florida",
    region: "South",
    x: 8,
    y: 8,
    value: 0,
  },
  {
    "hc-a2": "GA",
    name: "Georgia",
    region: "South",
    x: 7,
    y: 8,
    value: 0,
  },
  {
    "hc-a2": "HI",
    name: "Hawaii",
    region: "West",
    x: 8,
    y: 0,
    value: 0,
  },
  {
    "hc-a2": "ID",
    name: "Idaho",
    region: "West",
    x: 3,
    y: 2,
    value: 0,
  },
  {
    "hc-a2": "IL",
    name: "Illinois",
    region: "Midwest",
    x: 3,
    y: 6,
    value: 0,
  },
  {
    "hc-a2": "IN",
    name: "Indiana",
    region: "Midwest",
    x: 3,
    y: 7,
    value: 0,
  },
  {
    "hc-a2": "IA",
    name: "Iowa",
    region: "Midwest",
    x: 3,
    y: 5,
    value: 0,
  },
  {
    "hc-a2": "KS",
    name: "Kansas",
    region: "Midwest",
    x: 5,
    y: 5,
    value: 0,
  },
  {
    "hc-a2": "KY",
    name: "Kentucky",
    region: "South",
    x: 4,
    y: 6,
    value: 0,
  },
  {
    "hc-a2": "LA",
    name: "Louisiana",
    region: "South",
    x: 6,
    y: 5,
    value: 0,
  },
  {
    "hc-a2": "ME",
    name: "Maine",
    region: "Northeast",
    x: 0,
    y: 11,
    value: 0,
  },
  {
    "hc-a2": "MD",
    name: "Maryland",
    region: "South",
    x: 4,
    y: 8,
    value: 0,
  },
  {
    "hc-a2": "MA",
    name: "Massachusetts",
    region: "Northeast",
    x: 2,
    y: 10,
    value: 0,
  },
  {
    "hc-a2": "MI",
    name: "Michigan",
    region: "Midwest",
    x: 2,
    y: 7,
    value: 0,
  },
  {
    "hc-a2": "MN",
    name: "Minnesota",
    region: "Midwest",
    x: 2,
    y: 4,
    value: 0,
  },
  {
    "hc-a2": "MS",
    name: "Mississippi",
    region: "South",
    x: 6,
    y: 6,
    value: 0,
  },
  {
    "hc-a2": "MO",
    name: "Missouri",
    region: "Midwest",
    x: 4,
    y: 5,
    value: 0,
  },
  {
    "hc-a2": "MT",
    name: "Montana",
    region: "West",
    x: 2,
    y: 2,
    value: 0,
  },
  {
    "hc-a2": "NE",
    name: "Nebraska",
    region: "Midwest",
    x: 4,
    y: 4,
    value: 0,
  },
  {
    "hc-a2": "NV",
    name: "Nevada",
    region: "West",
    x: 4,
    y: 2,
    value: 0,
  },
  {
    "hc-a2": "NH",
    name: "New Hampshire",
    region: "Northeast",
    x: 1,
    y: 11,
    value: 0,
  },
  {
    "hc-a2": "NJ",
    name: "New Jersey",
    region: "Northeast",
    x: 3,
    y: 10,
    value: 0,
  },
  {
    "hc-a2": "NM",
    name: "New Mexico",
    region: "West",
    x: 6,
    y: 3,
    value: 0,
  },
  {
    "hc-a2": "NY",
    name: "New York",
    region: "Northeast",
    x: 2,
    y: 9,
    value: 0,
  },
  {
    "hc-a2": "NC",
    name: "North Carolina",
    region: "South",
    x: 5,
    y: 9,
    value: 0,
  },
  {
    "hc-a2": "ND",
    name: "North Dakota",
    region: "Midwest",
    x: 2,
    y: 3,
    value: 0,
  },
  {
    "hc-a2": "OH",
    name: "Ohio",
    region: "Midwest",
    x: 3,
    y: 8,
    value: 0,
  },
  {
    "hc-a2": "OK",
    name: "Oklahoma",
    region: "South",
    x: 6,
    y: 4,
    value: 0,
  },
  {
    "hc-a2": "OR",
    name: "Oregon",
    region: "West",
    x: 4,
    y: 1,
    value: 0,
  },
  {
    "hc-a2": "PA",
    name: "Pennsylvania",
    region: "Northeast",
    x: 3,
    y: 9,
    value: 0,
  },
  {
    "hc-a2": "RI",
    name: "Rhode Island",
    region: "Northeast",
    x: 2,
    y: 11,
    value: 0,
  },
  {
    "hc-a2": "SC",
    name: "South Carolina",
    region: "South",
    x: 6,
    y: 8,
    value: 0,
  },
  {
    "hc-a2": "SD",
    name: "South Dakota",
    region: "Midwest",
    x: 3,
    y: 4,
    value: 0,
  },
  {
    "hc-a2": "TN",
    name: "Tennessee",
    region: "South",
    x: 5,
    y: 7,
    value: 0,
  },
  {
    "hc-a2": "TX",
    name: "Texas",
    region: "South",
    x: 7,
    y: 4,
    value: 0,
  },
  {
    "hc-a2": "UT",
    name: "Utah",
    region: "West",
    x: 5,
    y: 4,
    value: 0,
  },
  {
    "hc-a2": "VT",
    name: "Vermont",
    region: "Northeast",
    x: 1,
    y: 10,
    value: 0,
  },
  {
    "hc-a2": "VA",
    name: "Virginia",
    region: "South",
    x: 5,
    y: 8,
    value: 0,
  },
  {
    "hc-a2": "WA",
    name: "Washington",
    region: "West",
    x: 2,
    y: 1,
    value: 0,
  },
  {
    "hc-a2": "WV",
    name: "West Virginia",
    region: "South",
    x: 4,
    y: 7,
    value: 0,
  },
  {
    "hc-a2": "WI",
    name: "Wisconsin",
    region: "Midwest",
    x: 2,
    y: 5,
    value: 0,
  },
  {
    "hc-a2": "WY",
    name: "Wyoming",
    region: "West",
    x: 3,
    y: 3,
    value: 0,
  },
];
